// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrbc5YJN7QXXbK0qyz-7F0n1ZFHtcLV1Y',
    appId: '1:565521565585:web:32b8f6c330fc4371287c30',
    messagingSenderId: '565521565585',
    projectId: 'deb-eroute',
    authDomain: 'deb-eroute.firebaseapp.com',
    databaseURL: 'https://deb-eroute-default-rtdb.firebaseio.com',
    storageBucket: 'deb-eroute.appspot.com',
    measurementId: 'G-EGKRM2Y08P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVIjF9KLUizqbKQ18xmtRSq5ec7I51XR8',
    appId: '1:565521565585:android:5489e36939b3facd287c30',
    messagingSenderId: '565521565585',
    projectId: 'deb-eroute',
    databaseURL: 'https://deb-eroute-default-rtdb.firebaseio.com',
    storageBucket: 'deb-eroute.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_9qDhcV-OWeyg1O4RoM1N6Af8RCV7BnA',
    appId: '1:565521565585:ios:a0a75f96cd2ed9fc287c30',
    messagingSenderId: '565521565585',
    projectId: 'deb-eroute',
    databaseURL: 'https://deb-eroute-default-rtdb.firebaseio.com',
    storageBucket: 'deb-eroute.appspot.com',
    iosBundleId: 'com.example.erouteadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_9qDhcV-OWeyg1O4RoM1N6Af8RCV7BnA',
    appId: '1:565521565585:ios:d410ca37ea3280cd287c30',
    messagingSenderId: '565521565585',
    projectId: 'deb-eroute',
    databaseURL: 'https://deb-eroute-default-rtdb.firebaseio.com',
    storageBucket: 'deb-eroute.appspot.com',
    iosBundleId: 'com.example.erouteadmin.RunnerTests',
  );
}
